# Generated by Django 4.2.6 on 2023-10-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarelo')], default='white', max_length=20),
        ),
    ]
